from io import BytesIO
from pathlib import Path
from typing import Any, Generator, List, Union

import PySimpleGUI as sg

from player.playlist import PlaylistItem

WINDOW_TIMEOUT: int

class CustomTable(sg.Table):
    RowHeaderText: str
    def __init__(self, *args, **kwargs) -> None: ...

class MousaiGUI:
    PLAY_BTN_SYMBOL: str
    PAUSE_BTN_SYMBOL: str
    audio_file_types: Any
    menu_layout: Any
    theme: Any
    player: Any
    layout: Any
    window: Any
    def __init__(self, theme: str = ...) -> None: ...
    def get_song_art(self, song_meta_art: Union[BytesIO, None]) -> bytes: ...
    def set_current_song(self, song: PlaylistItem) -> None: ...
    def create_layout(self) -> List[List[sg.Pane]]: ...
    def get_audio_file_paths(self) -> Union[None, Generator[Path, None, None]]: ...
    def get_audio_files_from_directory(
        self,
    ) -> Union[None, Generator[Path, None, None]]: ...
    def playlist_to_table(self) -> List[List[str]]: ...
    def set_metadata_frame(self) -> None: ...
    def set_timers(self, start: str = ...) -> None: ...
    def restart_current_song(self) -> None: ...
    def handle_volume_change(self, value: float) -> None: ...
    def run(self) -> None: ...
